# Generated by Django 3.0.8 on 2020-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('cdt', models.DateTimeField(auto_now_add=True)),
                ('udt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
