# Generated by Django 3.0.8 on 2020-07-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
