# Generated by Django 3.0.8 on 2020-07-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200717_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-cdt']},
        ),
    ]
